name: My First Workflow

on: 
  push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Message
        run: echo "My First Github Action Job"
      - name: List the files
        run: ls
      - name: Read file
        run: cat REAMDME.md
      